modLoader = "javafml"
loaderVersion = "[${loader_version},)"
license = "GNU LGPL 3.0"

[[mods]]
modId = "merchantjs"
version = "1.0.0"
displayName = "MerchantJS"
authors = "zhenshiz"
description = ""
logoFile = "icon.png"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.merchantjs]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.197,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.merchantjs]]
modId = "kubejs"
type = "required"
versionRange = "[2101.7.1-build.181,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.merchantjs]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.21.2)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "merchantjs.mixins.json"
